fragment webformElementOption on WebformElementOption {
  __typename
  title
  value
}

fragment webformElementRadios on WebformElementRadios {
  __typename
  id
  title
  description
  options {
    ...webformElementOption
  }
}

fragment webformElement on WebformElement {
  ...webformElementRadios
}

fragment webform on Webform {
  title
  elements {
    ...webformElement
  }
}

query webform($webform_id: String!) {
  form: webformById(webform_id: $webform_id) {
    ...webform
  }
}
